import { RfqRecord } from "@/types/b2b";

export const INITIAL_MOCK_RFQS: RfqRecord[] = [
  {
    id: "rfq_demo_102",
    rfqNumber: "RFQ-2026-000102",
    buyerName: "Marcus Vance",
    buyerEmail: "buyer@ayaanclothing.com",
    buyerPhone: "+44 20 7946 0912",
    companyName: "Vance & Co Retail Ltd",
    businessType: "Wholesaler",
    website: "https://vancestyle.co.uk",
    taxNumber: "GB987654321",
    destinationCountry: "United Kingdom",
    destinationCity: "London",
    shippingPort: "Port of Felixstowe / Heathrow Airport",
    targetDeliveryDate: "2026-10-15",
    requestTitle: "Autumn Knitwear & Heavyweight Hoodies Bulk Inquiry",
    generalNotes: "Looking for custom neck label branding and export carton polybags. Fast air sample dispatch requested.",
    status: "QUOTATION_PREPARED",
    items: [
      {
        id: "rfq_item_1",
        productId: "prd0001",
        productName: "Essential Cotton T-Shirt",
        productSlug: "essential-cotton-t-shirt",
        brand: "Levi's",
        sku: "LEVIS-TSH-M-BLK-M-PRD0001",
        image: "https://images.pexels.com/photos/7658459/pexels-photo-7658459.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        quantity: 500,
        moq: 50,
        unitPrice: 8.00,
        targetPrice: 7.50,
        buyerNotes: "Color breakdown: 300 Black, 200 White. Size run S-2XL.",
      },
    ],
    messages: [
      {
        id: "msg_1",
        rfqId: "rfq_demo_102",
        senderName: "Marcus Vance",
        senderRole: "buyer",
        message: "Can you provide quotation with CIF London air freight?",
        createdAt: "2026-08-20T10:00:00Z",
      },
      {
        id: "msg_2",
        rfqId: "rfq_demo_102",
        senderName: "Ayaan Admin",
        senderRole: "admin",
        message: "Quotation QT-2026-000102 generated with discounted Aramex priority air rates.",
        createdAt: "2026-08-21T14:30:00Z",
      },
    ],
    history: [
      {
        id: "hist_1",
        rfqId: "rfq_demo_102",
        status: "SUBMITTED",
        actorName: "Marcus Vance",
        note: "Initial RFQ submitted by buyer",
        createdAt: "2026-08-20T09:30:00Z",
      },
      {
        id: "hist_2",
        rfqId: "rfq_demo_102",
        status: "QUOTATION_PREPARED",
        actorName: "Ayaan Admin",
        note: "Quotation prepared and sent",
        createdAt: "2026-08-21T14:00:00Z",
      },
    ],
    createdAt: "2026-08-20T09:30:00Z",
    updatedAt: "2026-08-21T14:30:00Z",
  },
  {
    id: "rfq_demo_103",
    rfqNumber: "RFQ-2026-000103",
    buyerName: "Sarah Jenkins",
    buyerEmail: "testuser@example.com",
    buyerPhone: "+1-555-0199",
    companyName: "Jenkins Apparel Boutique",
    businessType: "Boutique Chain",
    destinationCountry: "United States",
    destinationCity: "Los Angeles",
    shippingPort: "Port of Long Beach",
    targetDeliveryDate: "2026-11-01",
    requestTitle: "Denim Jackets & Vintage Washed Pullovers Inquiry",
    generalNotes: "Initial trial batch for retail chain launch in California.",
    status: "SUBMITTED",
    items: [
      {
        id: "rfq_item_2",
        productId: "prd0002",
        productName: "Classic Denim Jacket",
        productSlug: "classic-denim-jacket",
        brand: "Ayaan",
        sku: "AYN-JNS-002",
        image: "https://images.pexels.com/photos/19490409/pexels-photo-19490409.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        quantity: 200,
        moq: 50,
        unitPrice: 32.00,
        targetPrice: 30.00,
        buyerNotes: "Assorted sizes: S:40, M:80, L:60, XL:20",
      },
    ],
    messages: [],
    history: [
      {
        id: "hist_3",
        rfqId: "rfq_demo_103",
        status: "SUBMITTED",
        actorName: "Sarah Jenkins",
        note: "Submitted RFQ for denim jacket trial run",
        createdAt: "2026-08-29T11:15:00Z",
      },
    ],
    createdAt: "2026-08-29T11:15:00Z",
    updatedAt: "2026-08-29T11:15:00Z",
  },
];
