import { BrandModel } from "@/services/brand.service";

/**
 * Baseline Mock Brands
 * Real apparel brands with official logos, slugs, and active status.
 */
export const INITIAL_MOCK_BRANDS: BrandModel[] = [
  {
    id: "br_ayaan",
    name: "Ayaan",
    slug: "ayaan",
    logo_url: "/logo.png",
    logo: "/logo.png",
    website: "https://ayaanclothing.com",
    sort_order: 1,
    is_active: true,
    products_count: 24,
  },
  {
    id: "br_nike",
    name: "Nike",
    slug: "nike",
    logo_url: "/brands/nike.svg",
    logo: "/brands/nike.svg",
    website: "https://nike.com",
    sort_order: 2,
    is_active: true,
    products_count: 18,
  },
  {
    id: "br_adidas",
    name: "Adidas",
    slug: "adidas",
    logo_url: "/brands/adidas.svg",
    logo: "/brands/adidas.svg",
    website: "https://adidas.com",
    sort_order: 3,
    is_active: true,
    products_count: 16,
  },
  {
    id: "br_levis",
    name: "Levi's",
    slug: "levis",
    logo_url: "/brands/levis.png",
    logo: "/brands/levis.png",
    website: "https://levi.com",
    sort_order: 4,
    is_active: true,
    products_count: 15,
  },
  {
    id: "br_puma",
    name: "Puma",
    slug: "puma",
    logo_url: "/brands/puma.png",
    logo: "/brands/puma.png",
    website: "https://puma.com",
    sort_order: 5,
    is_active: true,
    products_count: 12,
  },
  {
    id: "br_underarmour",
    name: "Under Armour",
    slug: "under-armour",
    logo_url: "/brands/under-armour.svg",
    logo: "/brands/under-armour.svg",
    website: "https://underarmour.com",
    sort_order: 6,
    is_active: true,
    products_count: 10,
  },
  {
    id: "br_zara",
    name: "Zara",
    slug: "zara",
    logo_url: "/brands/zara.png",
    logo: "/brands/zara.png",
    website: "https://zara.com",
    sort_order: 7,
    is_active: true,
    products_count: 14,
  },
  {
    id: "br_hm",
    name: "H&M",
    slug: "hm",
    logo_url: "/brands/hm.png",
    logo: "/brands/hm.png",
    website: "https://hm.com",
    sort_order: 8,
    is_active: true,
    products_count: 11,
  },
  {
    id: "br_newbalance",
    name: "New Balance",
    slug: "new-balance",
    logo_url: "/brands/new-balance.svg",
    logo: "/brands/new-balance.svg",
    website: "https://newbalance.com",
    sort_order: 9,
    is_active: true,
    products_count: 8,
  },
  {
    id: "br_calvinklein",
    name: "Calvin Klein",
    slug: "calvin-klein",
    logo_url: "/brands/calvin-klein.png",
    logo: "/brands/calvin-klein.png",
    website: "https://calvinklein.com",
    sort_order: 10,
    is_active: true,
    products_count: 9,
  },
];
